import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // Create categories
  const categories = [
    { name: "electronics", nameFr: "Électronique", nameMg: "Elektronika", icon: "laptop" },
    { name: "vehicles", nameFr: "Véhicules", nameMg: "Fiara", icon: "car" },
    { name: "property", nameFr: "Immobilier", nameMg: "Trano", icon: "home" },
    { name: "clothing", nameFr: "Vêtements", nameMg: "Akanjo", icon: "shirt" },
    { name: "furniture", nameFr: "Meubles", nameMg: "Fanaka", icon: "sofa" },
    { name: "appliances", nameFr: "Électroménager", nameMg: "Fitaovana", icon: "plug" },
    { name: "sports", nameFr: "Sports & Loisirs", nameMg: "Fanatanjahantena", icon: "trophy" },
    { name: "books", nameFr: "Livres", nameMg: "Boky", icon: "book" },
    { name: "services", nameFr: "Services", nameMg: "Serivisy", icon: "wrench" },
    { name: "other", nameFr: "Autres", nameMg: "Hafa", icon: "package" },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { name: cat.name },
      update: {},
      create: cat,
    });
  }

  // Create demo users
  const users = [
    { name: "Rakoto Jean", email: "rakoto@example.com", phone: "+261 34 12 345 67", city: "Antananarivo", district: "Analakely" },
    { name: "Rasoa Marie", email: "rasoa@example.com", phone: "+261 33 98 765 43", city: "Antananarivo", district: "Ivandry" },
    { name: "Rabe Pierre", email: "rabe@example.com", phone: "+261 32 11 222 33", city: "Toamasina", district: "Centre-ville" },
    { name: "Ravao Lala", email: "ravao@example.com", phone: "+261 34 55 666 77", city: "Antsirabe", district: "Centre-ville" },
    { name: "Randria Paul", email: "randria@example.com", phone: "+261 33 44 555 66", city: "Mahajanga", district: "Centre-ville" },
    { name: "Nirina Haja", email: "nirina@example.com", phone: "+261 32 77 888 99", city: "Fianarantsoa", district: "Haute-ville" },
  ];

  const createdUsers = [];
  for (const user of users) {
    const created = await prisma.user.upsert({
      where: { email: user.email },
      update: {},
      create: user,
    });
    createdUsers.push(created);
  }

  // Create demo products
  const products = [
    {
      title: "iPhone 13 Pro - Très bon état",
      description: "iPhone 13 Pro 256GB, couleur graphite. Très bon état, toujours utilisé avec coque et protection d'écran. Batterie à 89%. Livré avec chargeur et câble d'origine.",
      price: 1800000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "electronics",
      status: "available",
      city: "Antananarivo",
      district: "Analakely",
      userId: createdUsers[0].id,
    },
    {
      title: "Samsung Galaxy A54 neuf",
      description: "Samsung Galaxy A54 5G, 128GB, encore sous garantie. Acheté il y a 2 mois. Avec tous les accessoires d'origine.",
      price: 950000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "electronics",
      status: "available",
      city: "Antananarivo",
      district: "Ivandry",
      userId: createdUsers[1].id,
    },
    {
      title: "Toyota Hilux 2018 - Double Cabine",
      description: "Toyota Hilux 2018, double cabine, diesel, 4x4. 85 000 km. Très bien entretenu, carnet d'entretien à jour. Climatisation, vitres électriques.",
      price: 65000000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "vehicles",
      status: "available",
      city: "Antananarivo",
      district: "Andravoahangy",
      userId: createdUsers[0].id,
    },
    {
      title: "Moto Yamaha FZ 150cc",
      description: "Yamaha FZ 150cc, année 2022. Très bon état, faible kilométrage. Idéal pour la ville.",
      price: 4500000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "vehicles",
      status: "reserved",
      city: "Toamasina",
      district: "Centre-ville",
      userId: createdUsers[2].id,
    },
    {
      title: "Appartement T3 à Ivandry",
      description: "Bel appartement T3 à louer à Ivandry. 2 chambres, salon, cuisine équipée, salle de bain. Parking sécurisé. Proche commerces et transports.",
      price: 800000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "property",
      status: "available",
      city: "Antananarivo",
      district: "Ivandry",
      userId: createdUsers[1].id,
    },
    {
      title: "Canapé 3 places en cuir",
      description: "Canapé 3 places en cuir véritable, couleur marron. Excellent état, très confortable. Dimensions: 200x85x90 cm.",
      price: 350000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "furniture",
      status: "available",
      city: "Antananarivo",
      district: "Ankadifotsy",
      userId: createdUsers[0].id,
    },
    {
      title: "Machine à laver Samsung 7kg",
      description: "Machine à laver Samsung 7kg, automatique, chargement frontal. 2 ans d'utilisation. Fonctionne parfaitement.",
      price: 450000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "appliances",
      status: "available",
      city: "Antsirabe",
      district: "Centre-ville",
      userId: createdUsers[3].id,
    },
    {
      title: "Vélo VTT adulte",
      description: "VTT adulte 26 pouces, 21 vitesses. Cadre aluminium, freins à disque. Peu utilisé, en très bon état.",
      price: 280000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "sports",
      status: "available",
      city: "Antsirabe",
      district: "Ambohijanaka",
      userId: createdUsers[3].id,
    },
    {
      title: "Collection de livres scolaires",
      description: "Collection complète de manuels scolaires pour la classe de Terminale. Maths, Physique, SVT, Français, Anglais, Histoire-Géo.",
      price: 50000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "books",
      status: "available",
      city: "Fianarantsoa",
      district: "Haute-ville",
      userId: createdUsers[5].id,
    },
    {
      title: "Robe traditionnelle malgache",
      description: "Belle robe traditionnelle en lamba, faite à la main. Taille M/L. Parfaite pour les cérémonies.",
      price: 120000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "clothing",
      status: "available",
      city: "Antananarivo",
      district: "Analakely",
      userId: createdUsers[1].id,
    },
    {
      title: "Ordinateur portable HP ProBook",
      description: "HP ProBook 450 G8, Core i5 11ème gen, 8GB RAM, 256GB SSD. Bon état, batterie tient 4h. Idéal pour le travail et les études.",
      price: 1200000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "electronics",
      status: "available",
      city: "Antananarivo",
      district: "Ankorondrano",
      userId: createdUsers[0].id,
    },
    {
      title: "Réfrigérateur LG 250L",
      description: "Réfrigérateur LG 250 litres, double porte, classe A+. Silencieux et économique. Garantie 1 an restant.",
      price: 600000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "appliances",
      status: "sold",
      city: "Mahajanga",
      district: "Centre-ville",
      userId: createdUsers[4].id,
    },
    {
      title: "Service de plomberie",
      description: "Plombier professionnel avec 10 ans d'expérience. Installation, réparation, débouchage. Devis gratuit. Disponible 7j/7.",
      price: 0,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "services",
      status: "available",
      city: "Antananarivo",
      district: "Isotry",
      userId: createdUsers[0].id,
    },
    {
      title: "Table à manger + 6 chaises",
      description: "Ensemble table à manger en bois massif avec 6 chaises. Style rustique. Table: 180x90 cm. Très bon état.",
      price: 480000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "furniture",
      status: "available",
      city: "Toamasina",
      district: "Bazar-be",
      userId: createdUsers[2].id,
    },
    {
      title: "PlayStation 5 + 2 manettes",
      description: "PS5 édition disque avec 2 manettes DualSense et 3 jeux (FIFA 24, GTA V, Spider-Man). Excellent état.",
      price: 2200000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "electronics",
      status: "available",
      city: "Antananarivo",
      district: "Andravoahangy",
      userId: createdUsers[1].id,
    },
    {
      title: "Chaussures de sport Nike taille 42",
      description: "Nike Air Max 90, taille 42, portées quelques fois seulement. Comme neuves. Couleur noir/blanc.",
      price: 85000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "clothing",
      status: "available",
      city: "Antananarivo",
      district: "Ivandry",
      userId: createdUsers[0].id,
    },
    {
      title: "Terrain à bâtir 500m² Ivato",
      description: "Terrain plat de 500m², titré, clôturé. Situé à Ivato, proche aéroport. Accès facile, eau et électricité à proximité.",
      price: 45000000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "property",
      status: "available",
      city: "Antananarivo",
      district: "Ivandry",
      userId: createdUsers[1].id,
    },
    {
      title: "Guitare acoustique Yamaha",
      description: "Guitare acoustique Yamaha F310, parfaite pour débuter. Livrée avec housse et médiators. Bon état.",
      price: 180000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "sports",
      status: "available",
      city: "Fianarantsoa",
      district: "Haute-ville",
      userId: createdUsers[5].id,
    },
    {
      title: "Lot de vêtements bébé 0-12 mois",
      description: "Lot de 30 pièces: bodies, pyjamas, pantalons, t-shirts. Mixte, en bon état. Idéal pour une naissance.",
      price: 75000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "clothing",
      status: "available",
      city: "Mahajanga",
      district: "Amborovy",
      userId: createdUsers[4].id,
    },
    {
      title: "Climatiseur split LG 12000 BTU",
      description: "Climatiseur split LG 12000 BTU, réversible chaud/froid. Installation incluse dans le prix. Garantie constructeur.",
      price: 750000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "appliances",
      status: "reserved",
      city: "Toamasina",
      district: "Ankirihiry",
      userId: createdUsers[2].id,
    },
    {
      title: "Cours particuliers de mathématiques",
      description: "Professeur certifié donne cours particuliers de maths. Niveau collège et lycée. Possibilité de cours à domicile ou en ligne.",
      price: 15000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "services",
      status: "available",
      city: "Antananarivo",
      district: "Analakely",
      userId: createdUsers[5].id,
    },
    {
      title: "Bureau + chaise ergonomique",
      description: "Bureau en bois 120x60cm avec chaise ergonomique. Parfait pour le télétravail. Ensemble en très bon état.",
      price: 320000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "furniture",
      status: "available",
      city: "Antananarivo",
      district: "Ankorondrano",
      userId: createdUsers[0].id,
    },
    {
      title: "Imprimante Canon multifonction",
      description: "Canon PIXMA G3010, imprimante multifonction avec réservoir d'encre rechargeable. Impression, scan, copie, WiFi.",
      price: 380000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "electronics",
      status: "available",
      city: "Antsirabe",
      district: "Centre-ville",
      userId: createdUsers[3].id,
    },
    {
      title: "Tricycle pour enfant",
      description: "Tricycle en bon état pour enfant de 2-5 ans. Avec panier arrière et guidon parental amovible.",
      price: 45000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "sports",
      status: "available",
      city: "Antananarivo",
      district: "Isotry",
      userId: createdUsers[1].id,
    },
    {
      title: "Cuisinière à gaz 4 feux",
      description: "Cuisinière à gaz 4 feux avec four. Marque Beko. Très bon état, utilisée pendant 1 an seulement.",
      price: 280000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "appliances",
      status: "available",
      city: "Mahajanga",
      district: "Centre-ville",
      userId: createdUsers[4].id,
    },
    {
      title: "Dictionnaire Français-Malgache",
      description: "Grand dictionnaire Français-Malgache et Malgache-Français. Édition complète. Parfait état.",
      price: 25000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "books",
      status: "available",
      city: "Fianarantsoa",
      district: "Tsianolondroa",
      userId: createdUsers[5].id,
    },
    {
      title: "Scooter Kymco 125cc",
      description: "Scooter Kymco Agility 125cc, année 2021. 12 000 km. Bien entretenu, démarrage électrique.",
      price: 3800000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "vehicles",
      status: "available",
      city: "Antananarivo",
      district: "Andravoahangy",
      userId: createdUsers[0].id,
    },
    {
      title: "Matelas orthopédique 160x200",
      description: "Matelas orthopédique king size 160x200 cm. Épaisseur 25cm. Utilisé 6 mois, comme neuf. Housse lavable incluse.",
      price: 420000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "furniture",
      status: "available",
      city: "Toamasina",
      district: "Centre-ville",
      userId: createdUsers[2].id,
    },
    {
      title: "Service de déménagement",
      description: "Service de déménagement professionnel. Camion + 3 déménageurs. Tarif selon distance. Emballage fourni. Devis gratuit.",
      price: 0,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "services",
      status: "available",
      city: "Antananarivo",
      district: "Andravoahangy",
      userId: createdUsers[0].id,
    },
    {
      title: "Écran PC LG 27 pouces",
      description: "Moniteur LG 27 pouces Full HD, IPS. Ports HDMI et VGA. Pied réglable. Parfait pour le bureau ou le gaming.",
      price: 520000,
      images: JSON.stringify(["/images/placeholder.svg"]),
      category: "electronics",
      status: "available",
      city: "Antananarivo",
      district: "Ivandry",
      userId: createdUsers[1].id,
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }

  console.log("Seed completed: 10 categories, 6 users, 30 products");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
